version: '3.1'
services:
  casdoor:
    restart: always
    image: casbin/casdoor
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      RUNNING_IN_DOCKER: "true"
    volumes:
      - ./conf:/conf/
  db:
    restart: always
    image: postgres:16
    environment:
      - POSTGRES_DB=casdoordb
      - POSTGRES_USER=casdoor
      - POSTGRES_PASSWORD=casdoor
